-- Library importing
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

LIBRARY MY_LIB;
USE MY_LIB.ATOMIC_COMPONENTS.CONV_4_TO_7;

-- Package definition
PACKAGE COMPONENTS IS


END PACKAGE COMPONENTS;