-- Library importing
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

LIBRARY ATOMIC_COMPONENTS;
USE ATOMIC_COMPONENTS.ATOMIC_COMPONENTS.ALL;

ENTITY CPU IS:
    PORT(
        INSTRUCTION: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
        MUX_CONTROL: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        EN_CONTROL: OUT STD_LOGIC_VECTOR(7 DOWNTO 0) 
    );
END ENTITY CPU;

ARCHITECTURE ARCH_CPU OF CPU IS
    SIGNAL REG_MUX: STD_LOGIC_VECTOR(2 DOWNTO 0);
    SIGNAL REG_EN: STD_LOGIC_VECTOR(2 DOWNTO 0);
    SIGNAL RA, RB: STD_LOGIC_VECTOR(2 DOWNTO 0);

-- ISA: 
BEGIN
    MUX_CONTROL_DEC: DECODERN2
        GENERIC MAP(
            3
        )
        PORT MAP(
            REG_MUX,
            MUX_CONTROL

        );
    
    EN_CONTROL_DEC: DECODERN2
        GENERIC MAP(
            3
        )
        PORT MAP(
            REG_EN,
            EN_CONTROL

        );
    
    RA <= INSTRUCTION(5 DOWNTO 3);
    RB <= INSTRUCTION(2 DOWNTO 0);

CASE INSTRUCTION (7 DOWNTO 6) IS
    -- OPCODE 00 --> RA <= RB
    WHEN "00" => (REG_MUX <= RB AND REG_EN <= RA);
    -- OPCODE 01 --> ROUT <= RB
    WHEN "01" => (REG_MUX <= RB AND REG_EN <= "111");
    -- OPCODE 11 --> RA <= EXT_INPUT
    WHEN "11" => (REG_MUX <= "000" AND REG_EN <= RA);

END;


END ARCHITECTURE ARCH_CPU;