-- Library importing
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;

LIBRARY ATOMIC_COMPONENTS;
USE ATOMIC_COMPONENTS.ATOMIC_COMPONENTS.ALL;

ENTITY PARTE01 IS
	PORT(
    KEY: IN STD_LOGIC_VECTOR(1 DOWNTO 0); -- CLKR, ClearRegs
    SW: IN STD_LOGIC_VECTOR(12 DOWNTO 0); -- TecD, TecE, WrEn, SelM2, SelM1, SelRB, SelRA, AddSubR
    -- HEX0: OUT STD_LOGIC_VECTOR(6 DOWNTO 0); -- Data
    -- HEX1: OUT STD_LOGIC_VECTOR(6 DOWNTO 0); -- Data
    -- HEX6: OUT STD_LOGIC_VECTOR(6 DOWNTO 0); -- Address
    -- HEX7: OUT STD_LOGIC_VECTOR(6 DOWNTO 0); -- Address
    LEDG: OUT STD_LOGIC -- WrEn

	);
	
END ENTITY PARTE01;

ARCHITECTURE ARCH_PARTE01 OF PARTE01 IS

  SIGNAL CLKR, ClearRegs: STD_LOGIC;
  SIGNAL WrEn: STD_LOGIC_VECTOR(0 DOWNTO 0);
  SIGNAL TecD: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL TecE: STD_LOGIC_VECTOR(3 DOWNTO 0);

  SIGNAL ADD: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL DATA_IN: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL DATA_OUT: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL WR: STD_LOGIC_VECTOR (0 DOWNTO 0);

BEGIN
  CLKR <= KEY(0);
  ClearRegs <= KEY(1);

  TecD <= SW(7 DOWNTO 0);
  TecE <= SW(11 DOWNTO 8);

  WrEn(0) <= SW(12);

  FF_END: FLIP_FLOP_D
    GENERIC MAP(
        3
    )
    PORT MAP(
        CLKR,
        ClearRegs,
        TecE,
        ADD
    );

  FF_ENT_DADO: FLIP_FLOP_D
    GENERIC MAP(
        7
    )
    PORT MAP(
        CLKR,
        ClearRegs,
        TecD,
        DATA_IN
    );

  FF_ESCREVE: FLIP_FLOP_D
    GENERIC MAP(
        0
    )
    PORT MAP(
        CLKR,
        ClearRegs,
        WrEn,
        WR
    );


  RAM_16: RAM_32x8
      PORT MAP(
          ADD,
          DATA_IN,
          WR(0),
          CLKR,
          DATA_OUT
      );

END ARCHITECTURE ARCH_PARTE01;