-- Library importing
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;

LIBRARY ATOMIC_COMPONENTS;
USE ATOMIC_COMPONENTS.ATOMIC_COMPONENTS.ALL;

LIBRARY SUB_SYSTEMS;
USE SUB_SYSTEMS.SUB_SYSTEMS.ALL;

ENTITY PARTE01 IS
  PORT(
    X: IN STD_LOGIC;
    RST: IN STD_LOGIC;
    CLK: IN STD_LOGIC;
    Y: OUT STD_LOGIC  
  );
  
END ENTITY PARTE01;


ARCHITECTURE ARCH_PARTE01 OF PARTE01 IS
  SIGNAL BIT_ESTADO: STD_LOGIC_VECTOR(8 DOWNTO 0);
  SIGNAL ENTRADA_FF: STD_LOGIC_VECTOR(8 DOWNTO 0);

  
  BEGIN
    
    GEN_FFS: FOR i in 0 TO 8 GENERATE
      FFD_A: FLIP_FLOP_D
        GENERIC MAP(0)
          PORT MAP(
            CLK,
            RST,
            ENTRADA_FF(i DOWNTO i),
            BIT_ESTADO(i DOWNTO i)
        
          );
          
    END GENERATE;
    
    --A 
    ENTRADA_FF(0) <= '1';
    --B
    ENTRADA_FF(1) <= NOT(X) AND(BIT_ESTADO(0) OR BIT_ESTADO(5) OR BIT_ESTADO(6) OR BIT_ESTADO(7) OR BIT_ESTADO(8));
    --C
    ENTRADA_FF(2) <= NOT(X) AND BIT_ESTADO(1);
    --D
    ENTRADA_FF(3) <= NOT(X) AND BIT_ESTADO(2);
    --E
    ENTRADA_FF(4) <= NOT(X);
    --F
    ENTRADA_FF(5) <= X AND(BIT_ESTADO(0) OR BIT_ESTADO(1) OR BIT_ESTADO(2) OR BIT_ESTADO(3) OR BIT_ESTADO(4));
    --G
    ENTRADA_FF(6) <= X AND BIT_ESTADO(5);
    --H
    ENTRADA_FF(7) <= X AND BIT_ESTADO(6);
    --I
    ENTRADA_FF(8) <= X;
    
    Y <= BIT_ESTADO(4) OR BIT_ESTADO(8);
    
      


END ARCHITECTURE ARCH_PARTE01;