-- Library importing
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

LIBRARY ATOMIC_COMPONENTS;
USE ATOMIC_COMPONENTS.ATOMIC_COMPONENTS.ALL;

LIBRARY SUB_SYSTEMS;
USE SUB_SYSTEMS.SUB_SYSTEMS.ALL;

ENTITY PARTE01 IS
	PORT(
    KEY: IN STD_LOGIC_VECTOR(1 DOWNTO 0); -- clk, reset
    SW: IN STD_LOGIC_VECTOR(15 DOWNTO 0); -- ext input, instruction
    HEX0: OUT STD_LOGIC_VECTOR(6 DOWNTO 0); -- Disp1
    HEX1: OUT STD_LOGIC_VECTOR(6 DOWNTO 0) -- Disp2

	);
	
END ENTITY PARTE01;

ARCHITECTURE ARCH_PARTE01 OF PARTE01 IS

  TYPE REG_LIST IS ARRAY (0 TO 8) OF STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL REG_OUTPUT: REG_LIST;

  TYPE MUX_LIST IS ARRAY (0 TO 9) OF STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL MUX_OUTPUT: MUX_LIST;

	SIGNAL CLK, RST: STD_LOGIC;
  SIGNAL EXT_INPUT: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL INSTRUCTION: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL EN_CONTROL: STD_LOGIC_VECTOR(8 DOWNTO 0);
  SIGNAL MUX_CONTROL: STD_LOGIC_VECTOR(8 DOWNTO 0);
  SIGNAL DATA_PATH: STD_LOGIC_VECTOR(8 DOWNTO 0);

  SIGNAL BCD: STD_LOGIC_VECTOR (11 DOWNTO 0);

COMPONENT CPU IS:
    PORT(
        INSTRUCTION: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
        MUX_CONTROL: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
        EN_CONTROL: OUT STD_LOGIC_VECTOR(7 DOWNTO 0) 
    );
END COMPONENT CPU;

BEGIN
  CLK <= KEY(0);
  RST <= KEY(1);
  EXT_INPUT <= SW(7 DOWNTO 0);
  INSTRUCTION <= SW(15 DOWNTO 8);


  -- Registers
  GEN_REGS: FOR i IN 0 TO 8 GENERATE
    Reg(i): FLIP_FLOP_D
      GENERIC MAP(
          7
      )
      PORT MAP(
          CLK,
          RST,
          EN_CONTROL(i)
          DATA_PATH,
          REG_OUTPUT(i),
      );
    END GENERATE;

  
  -- MUX Declaration
  GEN_MUX: FOR i IN 1 TO 8 GENERATE
    MUX_OUTPUT(i) <= REG_OUTPUT(i);

  END GENERATE;

  MUX_OUTPUT(0) <= EXT_INPUT;

  DATA_PATH <= MUX_OUTPUT(TO_INTEGER(unsigned(MUX_CONTROL)));

  CPU_1: CPU
    PORT MAP(
      INSTRUCTION,
      MUX_CONTROL,
      EN_CONTROL
    );

  CONV_BIN2BCD: BIN2BCD
        PORT(
            REG_OUTPUT(8),
            BCD
        
    );

  HEX_0: CONV_4_TO_7
          PORT(
            BCD(3 DOWNTO 0),
            HEX0
        );

  HEX_1: CONV_4_TO_7
          PORT(
            BCD(7 DOWNTO 4),
            HEX1
        );
  

END ARCHITECTURE ARCH_PARTE01;